#!/usr/bin/env python
import unittest

class TestEjemplo(unittest.TestCase): #Formato de la herencia
	def test(self):
		pass #Numero automatico que regresa non
	det test_2(self):
		assertTrue(True)

if __name_=="_main_":#Si se esta ejecutando x modulo entonces hace este
	unittest.main()
